### ISSUE TITLE
Error: Tutorial -- Multiplayer Game

### ISSUE THREAD

**Issue by pkrasam** [nearprotocol/NEARStudio#91] opened 2019-02-28 02:44 UTC
<img width="650" alt="190228_near_protocol_tutorial_error" src="https://user-images.githubusercontent.com/4514654/53537634-c172c680-3b5e-11e9-81b6-509264a32d93.png">

[Tutorial](https://docs.nearprotocol.com/#/tutorials/multiplayergame)
[Studio](https://studio.nearprotocol.com/?f=fnpeopb37&quickstart)

Please Help!

**Comment by vgrichina** [comment] 2019-02-28 03:24
@pkrasam I tried forking your linked example – it built fine for me. Maybe try again after refreshing browser window?

**Comment by vgrichina** [comment] 2019-02-28 04:12
@pkrasam feel free to ping me on https://near.chat for realtime support. My username is same there.

**Comment by jason00111** [comment] 2019-03-05 02:35
I get a slightly different error, but I think this is the same bug as https://github.com/nearprotocol/docs/issues/15

**Comment by potatodepaulo** [comment] 2019-03-20 18:33
Hey this has been fixed in updated tutorial. Not a bug with studio, 👍

**Closed by potatodepaulo** 2019-03-20 18:33 UTC
